# Generated by Django 2.2.10 on 2021-10-29 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_auto_20211028_1600'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('total_price', models.IntegerField(default=0.0)),
                ('address', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=64)),
                ('zip', models.CharField(max_length=32)),
                ('note', models.CharField(blank=True, max_length=1024)),
                ('contact', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Pending', max_length=64)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.IntegerField(default=1)),
                ('item_cost', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=[('', '---------')], to='products.ProductColor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product', models.ForeignKey(on_delete=[('', '---------')], to='products.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
