# Generated by Django 2.2.10 on 2021-10-30 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='firstname',
            field=models.CharField(default=datetime.datetime(2021, 10, 30, 16, 29, 16, 525104, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='street1',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street2',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.Order'),
        ),
    ]
