# Generated by Django 2.2.10 on 2021-10-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211030_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
