# Generated by Django 2.2.10 on 2021-10-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='street2',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
