# Generated by Django 2.2.10 on 2021-10-26 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='note',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='contact',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
        migrations.RemoveField(
            model_name='product',
            name='province',
        ),
        migrations.RemoveField(
            model_name='product',
            name='street1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='street2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='zip',
        ),
    ]
